version: '2'
services:
  server:
    build:
      context: ./Database-Server/
    command: /usr/app/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./Database-Server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./
    command: npm start
    volumes:
      - ./:/usr/client
      - /usr/client/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"