version: '2'
services:
  server:
    build:
      context: ./Database-Server/
    command: /usr/app/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./Database-Server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  chat:
    build:
      context: ./Chat-Server/
    command: /usr/app/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./Chat-Server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  cookies:
    build:
      context: ./Cookies-Server/
    command: /usr/cookies/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./Cookies-Server/:/usr/cookies
      - /usr/cookies/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  cache:
    build:
      context: ./Cache-Server/
    command: /usr/cache/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./Cache-Server/:/usr/cache
      - /usr/cache/node_modules
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REDIS_SERVER_PORT=6060
  client:
    build:
      context: ./
    command: npm start
    volumes:
      - ./:/usr/client
      - /usr/client/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"